# Generated by Django 2.1.5 on 2019-11-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
